spring.application.name=auth-service
server.port=8081
spring.data.mongodb.uri=mongodb://localhost:27017/healthcare_auth
management.endpoints.web.exposure.include=health,info
spring.mvc.problemdetails.enabled=true
spring.config.import=optional:classpath:application-secret.properties
jwt.expiration=86400000