spring.application.name=auth-service
server.port=8081
spring.data.mongodb.uri=mongodb://localhost:27017/healthcare_auth
management.endpoints.web.exposure.include=health,info
spring.mvc.problemdetails.enabled=true